INSERT INTO tags (name, description, tag_type) VALUES
('init', '', 'SYSTEM'),

('Chinese', '', 'LANGUAGE'),
('Korean', '', 'LANGUAGE'),
('Japanese', '', 'LANGUAGE'),
('English', '', 'LANGUAGE'),

('Action', 'A work typically depicting fighting, violence, chaos, and fast paced motion.', 'GENRE'),
('Adult', '', 'GENRE'),
('Adventure', '', 'GENRE'),
('Comedy', '', 'GENRE'),
('Drama', '', 'GENRE'),
('Ecchi', '', 'GENRE'),
('Fantasy', '', 'GENRE'),
('Game', '', 'GENRE'),
('Gender Bender', '', 'GENRE'),
('Harem', '', 'GENRE'),
('Josei', '', 'GENRE'),
('Historical', '', 'GENRE'),
('Horror', '', 'GENRE'),
('Martial Arts', '', 'GENRE'),
('Mature', '', 'GENRE'),
('Mecha', '', 'GENRE'),
('Mystery', '', 'GENRE'),
('Psychological', '', 'GENRE'),
('Romance', '', 'GENRE'),
('School Life', '', 'GENRE'),
('Sci-fi', '', 'GENRE'),
('Seinen', '', 'GENRE'),
('Shoujo', '', 'GENRE'),
('Shounen', '', 'GENRE'),
('Slice of Life', '', 'GENRE'),
('Shounen Ai', '', 'GENRE'),
('Sports', '', 'GENRE'),
('Supernatural', '', 'GENRE'),
('Smut', '', 'GENRE'),
('Tragedy', '', 'GENRE'),
('Xianxia', '', 'GENRE'),
('Xuanhuan', '', 'GENRE'),
('Wuxia', '', 'GENRE'),
('Yaoi', '', 'GENRE'),
('Yuri', '', 'GENRE');