
INSERT INTO tags (name, description, tag_type) VALUES
('init', '', 'SYSTEM'),

('Chinese', '', 'LANGUAGE'),
('Korean', '', 'LANGUAGE'),
('Japanese', '', 'LANGUAGE'),
('English', '', 'LANGUAGE'),

('Action', 'A work typically depicting fighting, violence, chaos, and fast paced motion.', 'GENRE'),
('Adult', 'Contains mature content that is suitable only for adults. ' ||
          'Titles in this category may include prolonged scenes of intense ' ||
          'violence and/or graphic sexual content and nudity.', 'GENRE'),
('Adventure', 'Exploring new places, environments or situations. ' ||
              'This is often associated with people on long journeys to places far ' ||
              'away encountering amazing things.', 'GENRE'),
('Comedy', 'A dramatic work that is light and often humorous or satirical in tone and that ' ||
           'usually contains a happy resolution of the thematic conflict.', 'GENRE'),
('Drama', 'A work meant to bring on an emotional response, such as instilling sadness or tension. ' ||
          'Novels that often show life or characters through conflict and emotions. In general, ' ||
          'the different parts of the story tend to form a whole that is greater than the sum of ' ||
          'the parts. In other words, the story has a message that is bigger than just the story ' ||
          'line itself.', 'GENRE'),
('Ecchi', 'Possibly the line between hentai and non-hentai, ecchi usually refers to fanservice put in ' ||
          'to attract a certain group of fans.', 'GENRE'),
('Fantasy', 'Anything that involves, but not limited to, magic, dream world, and fairy tales.', 'GENRE'),
('Game', 'Novels related to game elements, or a similar system. For example: characters are immersed in ' ||
         'VR, God closed people in space with the system, technologies like a game (RealRPG) descended ' ||
         'into the world.
', 'GENRE'),
('Gender Bender', 'Girls dressing up as guys, guys dressing up as girls. Guys turning into girls, ' ||
                  'girls turning into guys.', 'GENRE'),
('Harem', 'A series involving one male character and many female characters (usually attracted to ' ||
          'the male character). A Reverse Harem is when the genders are reversed.', 'GENRE'),
('Josei', 'Literally [Woman]. Targets women 18-30. Female equivalent to seinen. Unlike shoujo ' ||
          'the romance is more realistic and less idealized. The storytelling is more explicit ' ||
          'and mature.', 'GENRE'),
('Historical', 'Novels whose setting is in the past. Frequently these follow historical tales, ' ||
               'sagas or facts. World with kingdom setting that are not from actual history saga, ' ||
               'tales, are not included.', 'GENRE'),
('Horror', 'Novels whose focus is to scare the audience.', 'GENRE'),
('Martial Arts', 'The novel has a focus on any of several arts of combat or self-defense. ' ||
                 'These may include aikido, karate, judo, or tae kwon do, kendo, fencing, and so ' ||
                 'on and so forth.', 'GENRE'),
('Mature', 'Contains subject matter which may be too extreme for a younger audience. ' ||
           'Content that deals with mature themes such as gore, sex, or violence.', 'GENRE'),
('Mecha', 'A work involving and usually concentrating on all types of large robotic machines.', 'GENRE'),
('Mystery', 'Usually an unexplained event occurs, and the main protagonist attempts to ' ||
            'find out what caused it.', 'GENRE'),
('Psychological', 'Usually deals with the philosophy of a state of mind, in most cases detailing ' ||
                  'abnormal psychology.', 'GENRE'),
('Romance', 'A story in this genre focus heavily on the romantic relationship between two or more people.',
                'GENRE'),
('School Life', 'Having a major setting of the story deal with some type of school.', 'GENRE'),
('Sci-fi', 'Short for science fiction, these works involve twists on technology and other ' ||
           'science related phenomena which are contrary or stretches of the modern day ' ||
           'scientific world.', 'GENRE'),
('Seinen', 'Seinen means ''Young Man.'' Novels that specifically targets young adult males ' ||
           'around the ages of 18 to 25 are Seinen titles. Typically the story lines deal with ' ||
           'the issues of adulthood.', 'GENRE'),
('Shoujo', 'A work intended and primarily written for females. Usually the story is from the point ' ||
           'of view of a young female protagonist and usually involves romance and drama.', 'GENRE'),
('Shounen', 'A work intended and primarily written for younger male audience. ' ||
            'These works usually involve, but not limited to, fighting and/or violence.', 'GENRE'),
('Slice of Life', 'Novels with no focused plot. ' ||
                  'This genre tends to be naturalistic and mainly focuses around the main characters ' ||
                  'and their everyday lives. Often there will be some philosophical ' ||
                  'perspectives regarding love, relationships, life etc. tied into the novel. ' ||
                  'The overall typical moods for this type of story are cheery and carefree, ' ||
                  'no-rush life for the characters.', 'GENRE'),
('Shounen Ai', 'Often synonymous with Yaoi, this can be thought of as somewhat less extreme and ' ||
               'only hints at a relationship between two males. [Boy''s Love], so to speak.', 'GENRE'),
('Sports', 'As the name suggests, story with sports as one of its main element. ' ||
           'Baseball, basketball, hockey, soccer, golf, and racing just to name a few.', 'GENRE'),
('Supernatural', 'Usually entails amazing and unexplained powers or events which ' ||
                 'defy the laws of physics.', 'GENRE'),
('Smut', 'Erotic work of fiction that''s mainly targeted toward females. ' ||
         'Smut stories often gives heavy focus on love and relationships ' ||
         'between the main characters.', 'GENRE'),
('Tragedy', 'Contains events resulting in great loss and misfortune.', 'GENRE'),
('Xianxia', 'Xianxia is fictional martial art stories where the main goal of ' ||
            'the population is cultivating to Immortality, ' ||
            'seeking eternal life and the pinnacle of strength. ' ||
            'Xianxia stories features supernatural elements, ' ||
            'influenced heavily by Chinese folklore / mythology. ' ||
            'Cultivation path in xianxia involves taoism/daoism elements. ' ||
            'If the story doesn''t mention the dao, odds are that it is not a Xianxia.
', 'GENRE'),
('Xuanhuan', 'Similar to xianxia, Xuanhuan may contain immortal cultivation. ' ||
             'However, unlike xianxia, which is more focused on becoming immortal and tighter ' ||
             'on chinese mythology, Xuanhuan is a broader, more loose genre. Basically, ' ||
             'if it''s a cultivation-based story, yet it contain elements of western fantasy, ' ||
             'such as sci-fi, or magic that''s not inherently eastern, then it is a xuanhuan.', 'GENRE'),
('Wuxia', 'Wuxia is a fictional stories about mortal humans who can achieve superhuman ability ' ||
          'through martial arts training or internal energy cultivation. ' ||
          'Wuxia is usually depicted in an ancient china setting. ' ||
          'Despite any existence of supernatural elements, characters in a wuxia are rarely ' ||
          'depicted reaching over 150 years of age. No immortality.', 'GENRE'),
('Yaoi', 'This work usually involves intimate relationships between men. ' ||
         'Mutually exclusive with shounen ai.', 'GENRE'),
('Yuri', 'This work usually involves intimate relationships between women. ' ||
         'Mutually exclusive with shoujo ai.', 'GENRE'),

('Abandoned Children', ' ', 'EVENT'),
('Ability Steal', ' ', 'EVENT'),
('Absent Parents', ' ', 'EVENT'),
('Absolute Duo', ' ', 'EVENT'),
('Abused Characters', ' ', 'EVENT'),
('Abusive Characters', ' ', 'EVENT'),
('Academy', ' ', 'EVENT'),
('Accelerated Growth', ' ', 'EVENT'),
('Acting', ' ', 'EVENT'),
('Action', ' ', 'EVENT'),
('Adapted Manhwa', ' ', 'EVENT'),
('Adapted to Anime', ' ', 'EVENT'),
('Adapted to Drama', ' ', 'EVENT'),
('Adapted to Drama CD', ' ', 'EVENT'),
('Adapted to Game', ' ', 'EVENT'),
('Adapted to Manga', ' ', 'EVENT'),
('Adapted to Manhua', ' ', 'EVENT'),
('Adapted to Manhwa', ' ', 'EVENT'),
('Adapted to Movie', ' ', 'EVENT'),
('Adapted to Visual Novel', ' ', 'EVENT'),
('Adopted Children', ' ', 'EVENT'),
('Adopted Protagonist', ' ', 'EVENT'),
('Adultery', ' ', 'EVENT'),
('ADVANCED', ' ', 'EVENT'),
('advanced technology', ' ', 'EVENT'),
('adventure', ' ', 'EVENT'),
('Adventurers', ' ', 'EVENT'),
('Affair', ' ', 'EVENT'),
('Against the Gods', ' ', 'EVENT'),
('Age Progression', ' ', 'EVENT'),
('Age Regression', ' ', 'EVENT'),
('Aggressive Characters', ' ', 'EVENT'),
('Akame Ga Kill', ' ', 'EVENT'),
('Akame ga Kill!', ' ', 'EVENT'),
('Aladdin', ' ', 'EVENT'),
('Alchemist', ' ', 'EVENT'),
('Alchemy', ' ', 'EVENT'),
('Aliens', ' ', 'EVENT'),
('All-Girls School', ' ', 'EVENT'),
('Alternate World', ' ', 'EVENT'),
('Amnesia', ' ', 'EVENT'),
('Amorality Protagonist', ' ', 'EVENT'),
('Amusement Park', ' ', 'EVENT'),
('An*l', ' ', 'EVENT'),
('Anal', ' ', 'EVENT'),
('Ancient China', ' ', 'EVENT'),
('Ancient Times', ' ', 'EVENT'),
('Androgynous Characters', ' ', 'EVENT'),
('Androids', ' ', 'EVENT'),
('Angels', ' ', 'EVENT'),
('Angst', ' ', 'EVENT'),
('Animal Characteristics', ' ', 'EVENT'),
('Animal Rearing', ' ', 'EVENT'),
('Anti-Hero Lead', ' ', 'EVENT'),
('Anti-Magic', ' ', 'EVENT'),
('Anti-social Protagonist', ' ', 'EVENT'),
('Antihero Protagonist', ' ', 'EVENT'),
('Antique Shop', ' ', 'EVENT'),
('Apartment Life', ' ', 'EVENT'),
('Apathetic Protagonist', ' ', 'EVENT'),
('Apocalypse', ' ', 'EVENT'),
('Apocalyptic', ' ', 'EVENT'),
('Appearance Changes', ' ', 'EVENT'),
('Appearance Different from Actual Age', ' ', 'EVENT'),
('Archery', ' ', 'EVENT'),
('Aristocracy', ' ', 'EVENT'),
('Arms Dealers', ' ', 'EVENT'),
('Army', ' ', 'EVENT'),
('Army Building', ' ', 'EVENT'),
('Arranged Marriage', ' ', 'EVENT'),
('Arrogant Characters', ' ', 'EVENT'),
('Artifact Crafting', ' ', 'EVENT'),
('Artifacts', ' ', 'EVENT'),
('Artifacts Cultivation', ' ', 'EVENT'),
('Artificial Intelligence', ' ', 'EVENT'),
('Artists', ' ', 'EVENT'),
('Asexual Protagonist', ' ', 'EVENT'),
('ASOIAF', ' ', 'EVENT'),
('Assassins', ' ', 'EVENT'),
('Astrologers', ' ', 'EVENT'),
('Attack on Titan', ' ', 'EVENT'),
('Attractive Lead', ' ', 'EVENT'),
('Autism', ' ', 'EVENT'),
('Automatons', ' ', 'EVENT'),
('Avatar', ' ', 'EVENT'),
('Avatar: The Last Airbender', ' ', 'EVENT'),
('Average-looking Protagonist', ' ', 'EVENT'),
('Award-winning Work', ' ', 'EVENT'),
('Awkward Protagonist', ' ', 'EVENT'),
('Bands', ' ', 'EVENT'),
('Baseball', ' ', 'EVENT'),
('Based on a Movie', ' ', 'EVENT'),
('Based on a Song', ' ', 'EVENT'),
('Based on a TV Show', ' ', 'EVENT'),
('Based on a Video Game', ' ', 'EVENT'),
('Based on a Visual Novel', ' ', 'EVENT'),
('Based on an Anime', ' ', 'EVENT'),
('Basketball', ' ', 'EVENT'),
('Battle Academy', ' ', 'EVENT'),
('Battle Competition', ' ', 'EVENT'),
('Battle Through the Heavens', ' ', 'EVENT'),
('BDSM', ' ', 'EVENT'),
('Beast Companions', ' ', 'EVENT'),
('Beast Master', ' ', 'EVENT'),
('Beastkin', ' ', 'EVENT'),
('Beasts', ' ', 'EVENT'),
('Beautiful Couple', ' ', 'EVENT'),
('Beautiful Female Lead', ' ', 'EVENT'),
('Bestiality', ' ', 'EVENT'),
('Betrayal', ' ', 'EVENT'),
('Bickering Couple', ' ', 'EVENT'),
('Biochip', ' ', 'EVENT'),
('Bisexual Protagonist', ' ', 'EVENT'),
('Black Belly', ' ', 'EVENT'),
('Blackmail', ' ', 'EVENT'),
('Blacksmith', ' ', 'EVENT'),
('Bleach', ' ', 'EVENT'),
('Blind Dates', ' ', 'EVENT'),
('Blind Protagonist', ' ', 'EVENT'),
('Blood Manipulation', ' ', 'EVENT'),
('Bloodlines', ' ', 'EVENT'),
('Body Swap', ' ', 'EVENT'),
('Body Tempering', ' ', 'EVENT'),
('Body-double', ' ', 'EVENT'),
('Bodyguards', ' ', 'EVENT'),
('Books', ' ', 'EVENT'),
('Bookworm', ' ', 'EVENT'),
('Boss-Subordinate Relationship', ' ', 'EVENT'),
('Brainwashing', ' ', 'EVENT'),
('Breast Fetish', ' ', 'EVENT'),
('Broken Engagement', ' ', 'EVENT'),
('Brother Complex', ' ', 'EVENT'),
('Brotherhood', ' ', 'EVENT'),
('Buddhism', ' ', 'EVENT'),
('Bullying', ' ', 'EVENT'),
('Business', ' ', 'EVENT'),
('Business Management', ' ', 'EVENT'),
('Businessmen', ' ', 'EVENT'),
('Butlers', ' ', 'EVENT'),
('C*nnilingus', ' ', 'EVENT'),
('Call of Cthulhu', ' ', 'EVENT'),
('Calm Protagonist', ' ', 'EVENT'),
('Campione!', ' ', 'EVENT'),
('Cannibalism', ' ', 'EVENT'),
('Card Games', ' ', 'EVENT'),
('Carefree Protagonist', ' ', 'EVENT'),
('Caring Protagonist', ' ', 'EVENT'),
('Cautious Protagonist', ' ', 'EVENT'),
('Celebrities', ' ', 'EVENT'),
('CEO', ' ', 'EVENT'),
('Chapters  Reviews', ' ', 'EVENT'),
('Character Development', ' ', 'EVENT'),
('Character Growth', ' ', 'EVENT'),
('Charismatic Protagonist', ' ', 'EVENT'),
('Charlotte (anime)', ' ', 'EVENT'),
('Charming Protagonist', ' ', 'EVENT'),
('Chat Rooms', ' ', 'EVENT'),
('Chatgroup', ' ', 'EVENT'),
('Cheat', ' ', 'EVENT'),
('Cheats', ' ', 'EVENT'),
('Chefs', ' ', 'EVENT'),
('Child Abuse', ' ', 'EVENT'),
('Child Protagonist', ' ', 'EVENT'),
('Childcare', ' ', 'EVENT'),
('Childhood Friends', ' ', 'EVENT'),
('Childhood Love', ' ', 'EVENT'),
('Childhood Promise', ' ', 'EVENT'),
('Childish Protagonist', ' ', 'EVENT'),
('Chin', ' ', 'EVENT'),
('Chivalry of a Failed Knight', ' ', 'EVENT'),
('Chuunibyou', ' ', 'EVENT'),
('Clan Building', ' ', 'EVENT'),
('Clans', ' ', 'EVENT'),
('Classic', ' ', 'EVENT'),
('Clever Protagonist', ' ', 'EVENT'),
('Clever Protagonist Cultivation', ' ', 'EVENT'),
('Cliche', ' ', 'EVENT'),
('Cliffhangers', ' ', 'EVENT'),
('Clingy Lover', ' ', 'EVENT'),
('Clones', ' ', 'EVENT'),
('Clubs', ' ', 'EVENT'),
('Clumsy Love Interests', ' ', 'EVENT'),
('Co-Workers', ' ', 'EVENT'),
('Cohabitation', ' ', 'EVENT'),
('Cold Love Interests', ' ', 'EVENT'),
('Cold Protagonist', ' ', 'EVENT'),
('Collection of Short Stories', ' ', 'EVENT'),
('College or University', ' ', 'EVENT'),
('College/University', ' ', 'EVENT'),
('Coma', ' ', 'EVENT'),
('Comedic Undertone', ' ', 'EVENT'),
('comedy', ' ', 'EVENT'),
('Coming of Age', ' ', 'EVENT'),
('Complex Family Relationships', ' ', 'EVENT'),
('Conditional Power', ' ', 'EVENT'),
('Confident Protagonist', ' ', 'EVENT'),
('Confinement', ' ', 'EVENT'),
('Conflicting Loyalties', ' ', 'EVENT'),
('Conspiracies', ' ', 'EVENT'),
('Contemporary', ' ', 'EVENT'),
('Contracts', ' ', 'EVENT'),
('Cooking', ' ', 'EVENT'),
('Corruption', ' ', 'EVENT'),
('Cosmic Wars', ' ', 'EVENT'),
('Cosplay', ' ', 'EVENT'),
('Counter-Strike', ' ', 'EVENT'),
('Couple Growth', ' ', 'EVENT'),
('Court Official', ' ', 'EVENT'),
('Cousins', ' ', 'EVENT'),
('Cowardly Protagonist', ' ', 'EVENT'),
('Crafting', ' ', 'EVENT'),
('Crazy Protagonist', ' ', 'EVENT'),
('Crime', ' ', 'EVENT'),
('Criminals', ' ', 'EVENT'),
('Cross-dressing', ' ', 'EVENT'),
('Crossover', ' ', 'EVENT'),
('Cruel Characters', ' ', 'EVENT'),
('Cryostasis', ' ', 'EVENT'),
('Cultivation', ' ', 'EVENT'),
('Cunning Protagonist', ' ', 'EVENT'),
('Curious Protagonist', ' ', 'EVENT'),
('Curses', ' ', 'EVENT'),
('Cute Children', ' ', 'EVENT'),
('Cute Protagonist', ' ', 'EVENT'),
('Cute Story', ' ', 'EVENT'),
('Cyberpunk', ' ', 'EVENT'),
('Dancers', ' ', 'EVENT'),
('DanMachi', ' ', 'EVENT'),
('Dao Companion', ' ', 'EVENT'),
('Dao Comprehension', ' ', 'EVENT'),
('Daoism', ' ', 'EVENT'),
('Dark', ' ', 'EVENT'),
('Dark Souls', ' ', 'EVENT'),
('DC', ' ', 'EVENT'),
('DC Universe', ' ', 'EVENT'),
('Dead Protagonist', ' ', 'EVENT'),
('Death', ' ', 'EVENT'),
('Death of Loved Ones', ' ', 'EVENT'),
('Debts', ' ', 'EVENT'),
('Delinquents', ' ', 'EVENT'),
('Delusions', ' ', 'EVENT'),
('Demi-Humans', ' ', 'EVENT'),
('Demon Lord', ' ', 'EVENT'),
('Demon Slayer', ' ', 'EVENT'),
('Demonic Cultivation Technique', ' ', 'EVENT'),
('Demons', ' ', 'EVENT'),
('Dense Protagonist', ' ', 'EVENT'),
('Depictions of Cruelty', ' ', 'EVENT'),
('Depression', ' ', 'EVENT'),
('Destiny', ' ', 'EVENT'),
('Detective Conan', ' ', 'EVENT'),
('Detectives', ' ', 'EVENT'),
('Determined Protagonist', ' ', 'EVENT'),
('DEVIL', ' ', 'EVENT'),
('Devils', ' ', 'EVENT'),
('Devoted Love Interests', ' ', 'EVENT'),
('Dieselpunk', ' ', 'EVENT'),
('Different Social Status', ' ', 'EVENT'),
('Diplomacy', ' ', 'EVENT'),
('Disabilities', ' ', 'EVENT'),
('Discrimination', ' ', 'EVENT'),
('Disfigurement', ' ', 'EVENT'),
('Dishonest Protagonist', ' ', 'EVENT'),
('Distrustful Protagonist', ' ', 'EVENT'),
('Divination', ' ', 'EVENT'),
('Divination Enlightenment', ' ', 'EVENT'),
('Divine Protection', ' ', 'EVENT'),
('Divorce', ' ', 'EVENT'),
('Doctors', ' ', 'EVENT'),
('Dolls or Puppets', ' ', 'EVENT'),
('Dolls/Puppets', ' ', 'EVENT'),
('Domestic Affairs', ' ', 'EVENT'),
('doppelganger', ' ', 'EVENT'),
('Doting Love Interests', ' ', 'EVENT'),
('Doting Older Siblings', ' ', 'EVENT'),
('Doting Parents', ' ', 'EVENT'),
('Doulou Dalu', ' ', 'EVENT'),
('Douluo Dalu', ' ', 'EVENT'),
('Dragon', ' ', 'EVENT'),
('Dragon Ball', ' ', 'EVENT'),
('Dragon Riders', ' ', 'EVENT'),
('Dragon Slayers', ' ', 'EVENT'),
('Dragons', ' ', 'EVENT'),
('Drama', ' ', 'EVENT'),
('Dream', ' ', 'EVENT'),
('Dreams', ' ', 'EVENT'),
('Drugs', ' ', 'EVENT'),
('Druids', ' ', 'EVENT'),
('Dungeon', ' ', 'EVENT'),
('Dungeon Master', ' ', 'EVENT'),
('Dungeons', ' ', 'EVENT'),
('Dwarfs', ' ', 'EVENT'),
('Dwarves', ' ', 'EVENT'),
('Dystopia', ' ', 'EVENT'),
('e-Sports', ' ', 'EVENT'),
('Early Romance', ' ', 'EVENT'),
('Earth Invasion', ' ', 'EVENT'),
('Eastern Setting', ' ', 'EVENT'),
('Easy Going Life', ' ', 'EVENT'),
('Economics', ' ', 'EVENT'),
('egoist', ' ', 'EVENT'),
('Egoist Protagonist', ' ', 'EVENT'),
('Eidetic Memory', ' ', 'EVENT'),
('Elderly Protagonist', ' ', 'EVENT'),
('Elemental Magic', ' ', 'EVENT'),
('Elementalists', ' ', 'EVENT'),
('Elves', ' ', 'EVENT'),
('Emotionally Weak Protagonist', ' ', 'EVENT'),
('Empire', ' ', 'EVENT'),
('Empires', ' ', 'EVENT'),
('Enemies', ' ', 'EVENT'),
('Enemies Become Allies', ' ', 'EVENT'),
('Enemies Become Lovers', ' ', 'EVENT'),
('Engagement', ' ', 'EVENT'),
('Engineer', ' ', 'EVENT'),
('Enlightenment', ' ', 'EVENT'),
('Entertainment', ' ', 'EVENT'),
('Episodic', ' ', 'EVENT'),
('Eunuch', ' ', 'EVENT'),
('European Ambience', ' ', 'EVENT'),
('Evil Gods', ' ', 'EVENT'),
('Evil Organization', ' ', 'EVENT'),
('Evil Organizations', ' ', 'EVENT'),
('Evil Protagonist', ' ', 'EVENT'),
('Evil Religions', ' ', 'EVENT'),
('Evolution', ' ', 'EVENT'),
('Exhibitionism', ' ', 'EVENT'),
('Exorcism', ' ', 'EVENT'),
('Experiments', ' ', 'EVENT'),
('Eye Powers', ' ', 'EVENT'),
('F*llatio', ' ', 'EVENT'),
('Face Slapping', ' ', 'EVENT'),
('Fairies', ' ', 'EVENT'),
('Fairy Tail', ' ', 'EVENT'),
('Fallen Angels', ' ', 'EVENT'),
('Fallen Nobility', ' ', 'EVENT'),
('Fallout', ' ', 'EVENT'),
('Fallout: New Vegas', ' ', 'EVENT'),
('Familial Love', ' ', 'EVENT'),
('Familiars', ' ', 'EVENT'),
('Family', ' ', 'EVENT'),
('Family Business', ' ', 'EVENT'),
('Family Conflict', ' ', 'EVENT'),
('Famous Parents', ' ', 'EVENT'),
('Famous Protagonist', ' ', 'EVENT'),
('Fan-fiction', ' ', 'EVENT'),
('Fanaticism', ' ', 'EVENT'),
('Fanfiction', ' ', 'EVENT'),
('Fantasy', ' ', 'EVENT'),
('Fantasy Creatures', ' ', 'EVENT'),
('Fantasy Magic', ' ', 'EVENT'),
('Fantasy World', ' ', 'EVENT'),
('Farming', ' ', 'EVENT'),
('Fast Cultivation', ' ', 'EVENT'),
('Fast Learner', ' ', 'EVENT'),
('Fat Protagonist', ' ', 'EVENT'),
('Fat to Fit', ' ', 'EVENT'),
('Fate/Grand Order', ' ', 'EVENT'),
('Fate/stay night', ' ', 'EVENT'),
('Fated Lovers', ' ', 'EVENT'),
('Fearless Protagonist', ' ', 'EVENT'),
('Fellatio', ' ', 'EVENT'),
('Female Lead', ' ', 'EVENT'),
('Female Master', ' ', 'EVENT'),
('Female Protagonist', ' ', 'EVENT'),
('Female to Male', ' ', 'EVENT'),
('Feng Shui', ' ', 'EVENT'),
('Firearms', ' ', 'EVENT'),
('First Contact', ' ', 'EVENT'),
('First Love', ' ', 'EVENT'),
('First-time Interc**rse', ' ', 'EVENT'),
('First-time Intercourse', ' ', 'EVENT'),
('Flashbacks', ' ', 'EVENT'),
('Fleet Battles', ' ', 'EVENT'),
('Folklore', ' ', 'EVENT'),
('Food Shopkeeper', ' ', 'EVENT'),
('Forced into a Relationship', ' ', 'EVENT'),
('Forced Living Arrangements', ' ', 'EVENT'),
('Forced Marriage', ' ', 'EVENT'),
('Forgetful Protagonist', ' ', 'EVENT'),
('Forging', ' ', 'EVENT'),
('Former Hero', ' ', 'EVENT'),
('Found Family', ' ', 'EVENT'),
('Fourth Disaster', ' ', 'EVENT'),
('Fourth Wall', ' ', 'EVENT'),
('Fox Spirits', ' ', 'EVENT'),
('Friends Become Enemies', ' ', 'EVENT'),
('Friendship', ' ', 'EVENT'),
('Frieren', ' ', 'EVENT'),
('From the first POV', ' ', 'EVENT'),
('Full Metal Alchemist', ' ', 'EVENT'),
('Futanari', ' ', 'EVENT'),
('Future Civilization', ' ', 'EVENT'),
('Futuristic Setting', ' ', 'EVENT'),
('Galge', ' ', 'EVENT'),
('Gambling', ' ', 'EVENT'),
('Game', ' ', 'EVENT'),
('Game Element', ' ', 'EVENT'),
('Game Elements', ' ', 'EVENT'),
('Game of Thrones', ' ', 'EVENT'),
('Game Ranking System', ' ', 'EVENT'),
('GameLit', ' ', 'EVENT'),
('Gamer', ' ', 'EVENT'),
('Gamers', ' ', 'EVENT'),
('Gaming/E-Sport', ' ', 'EVENT'),
('Gandam', ' ', 'EVENT'),
('Gangs', ' ', 'EVENT'),
('Gate to Another World', ' ', 'EVENT'),
('Gender Bender', ' ', 'EVENT'),
('Genderless Protagonist', ' ', 'EVENT'),
('Generals', ' ', 'EVENT'),
('Genetic Modifications', ' ', 'EVENT'),
('Genius Protagonist', ' ', 'EVENT'),
('Genshin Impact', ' ', 'EVENT'),
('Ghosts', ' ', 'EVENT'),
('Gintama', ' ', 'EVENT'),
('Girl''s Love Subplot', ' ', 'EVENT'),
('Girls Love', ' ', 'EVENT'),
('Gladiators', ' ', 'EVENT'),
('Glasses-wearing Love Interests', ' ', 'EVENT'),
('Glasses-wearing Protagonist', ' ', 'EVENT'),
('Goblins', ' ', 'EVENT'),
('God Protagonist', ' ', 'EVENT'),
('God-human Relationship', ' ', 'EVENT'),
('Goddess', ' ', 'EVENT'),
('Goddesses', ' ', 'EVENT'),
('Godly Powers', ' ', 'EVENT'),
('Gods', ' ', 'EVENT'),
('Godzilla', ' ', 'EVENT'),
('Golems', ' ', 'EVENT'),
('Gore', ' ', 'EVENT'),
('Gothic', ' ', 'EVENT'),
('Grave Keepers', ' ', 'EVENT'),
('Grimdark', ' ', 'EVENT'),
('Grinding', ' ', 'EVENT'),
('Guardian Relationship', ' ', 'EVENT'),
('Guideverse', ' ', 'EVENT'),
('Guilds', ' ', 'EVENT'),
('Gunfighters', ' ', 'EVENT'),
('Guns', ' ', 'EVENT'),
('H*ndjob', ' ', 'EVENT'),
('Hackers', ' ', 'EVENT'),
('Half-human Protagonist', ' ', 'EVENT'),
('Handjob', ' ', 'EVENT'),
('Handsome Male Lead', ' ', 'EVENT'),
('Hard Sci-fi', ' ', 'EVENT'),
('Hard-Working Protagonist', ' ', 'EVENT'),
('Harem', ' ', 'EVENT'),
('Harem-seeking Protagonist', ' ', 'EVENT'),
('Harry Potter', ' ', 'EVENT'),
('Harsh Training', ' ', 'EVENT'),
('Hated Protagonist', ' ', 'EVENT'),
('Healers', ' ', 'EVENT'),
('Healing', ' ', 'EVENT'),
('Heartwarming', ' ', 'EVENT'),
('Heaven', ' ', 'EVENT'),
('Heavenly Tribulation', ' ', 'EVENT'),
('Hell', ' ', 'EVENT'),
('Helpful Protagonist', ' ', 'EVENT'),
('Hentai', ' ', 'EVENT'),
('Herbalist', ' ', 'EVENT'),
('Heroes', ' ', 'EVENT'),
('Heterochromia', ' ', 'EVENT'),
('Hidden Abilities', ' ', 'EVENT'),
('Hidden Gem', ' ', 'EVENT'),
('Hiding Identity', ' ', 'EVENT'),
('Hiding True Abilities', ' ', 'EVENT'),
('Hiding True Identity', ' ', 'EVENT'),
('High Fantasy', ' ', 'EVENT'),
('High School DxD', ' ', 'EVENT'),
('highiq', ' ', 'EVENT'),
('Highschool DxD', ' ', 'EVENT'),
('Highschool of the Dead', ' ', 'EVENT'),
('Hikikomori', ' ', 'EVENT'),
('history', ' ', 'EVENT'),
('Hokage', ' ', 'EVENT'),
('Hollywood', ' ', 'EVENT'),
('Homunculus', ' ', 'EVENT'),
('Honest Protagonist', ' ', 'EVENT'),
('Hospital', ' ', 'EVENT'),
('Hot-blooded Protagonist', ' ', 'EVENT'),
('Human Experimentation', ' ', 'EVENT'),
('Human Weapon', ' ', 'EVENT'),
('Human-Nonhuman Relationship', ' ', 'EVENT'),
('Humanoid Protagonist', ' ', 'EVENT'),
('Hunter × Hunter', ' ', 'EVENT'),
('Hunter X Hunter', ' ', 'EVENT'),
('Hunters', ' ', 'EVENT'),
('Hypnotism', ' ', 'EVENT'),
('Identity Crisis', ' ', 'EVENT'),
('Imaginary Friend', ' ', 'EVENT'),
('Immortals', ' ', 'EVENT'),
('Imperial Harem', ' ', 'EVENT'),
('Incest', ' ', 'EVENT'),
('Incubus', ' ', 'EVENT'),
('Indecisive Protagonist', ' ', 'EVENT'),
('Industrialization', ' ', 'EVENT'),
('Inferiority Complex', ' ', 'EVENT'),
('Infinite Flow', ' ', 'EVENT'),
('Inheritance', ' ', 'EVENT'),
('Inscriptions', ' ', 'EVENT'),
('Insects', ' ', 'EVENT'),
('Interconnected Storylines', ' ', 'EVENT'),
('Interdimensional Travel', ' ', 'EVENT'),
('Introverted Protagonist', ' ', 'EVENT'),
('Investigations', ' ', 'EVENT'),
('Invisibility', ' ', 'EVENT'),
('Is It Wrong to Try to Pick Up Girls in a Dungeon', ' ', 'EVENT'),
('Isekai', ' ', 'EVENT'),
('Jack of All Trades', ' ', 'EVENT'),
('Jealousy', ' ', 'EVENT'),
('Jiangshi', ' ', 'EVENT'),
('Jobless Class', ' ', 'EVENT'),
('JoJo''s Bizarre Adventure', ' ', 'EVENT'),
('Jujutsu Kaisen', ' ', 'EVENT'),
('Kakashi', ' ', 'EVENT'),
('Kanojo Okarishimasu', ' ', 'EVENT'),
('Karma', ' ', 'EVENT'),
('Kendo', ' ', 'EVENT'),
('Kenichi: The Mightiest Disciple', ' ', 'EVENT'),
('Kidnappings', ' ', 'EVENT'),
('Kind Love Interests', ' ', 'EVENT'),
('Kingdom Building', ' ', 'EVENT'),
('Kingdoms', ' ', 'EVENT'),
('Kingdoms Knights', ' ', 'EVENT'),
('Knights', ' ', 'EVENT'),
('Knights Level System', ' ', 'EVENT'),
('Kung Fu Panda', ' ', 'EVENT'),
('Kuudere', ' ', 'EVENT'),
('Lack of Common Sense', ' ', 'EVENT'),
('Language Barrier', ' ', 'EVENT'),
('Late Romance', ' ', 'EVENT'),
('Lawyers', ' ', 'EVENT'),
('Lazy Protagonist', ' ', 'EVENT'),
('Leadership', ' ', 'EVENT'),
('Legacies', ' ', 'EVENT'),
('Legends', ' ', 'EVENT'),
('leonine', ' ', 'EVENT'),
('Level System', ' ', 'EVENT'),
('LEVELUP', ' ', 'EVENT'),
('LGBTQA', ' ', 'EVENT'),
('Library', ' ', 'EVENT'),
('Limited Lifespan', ' ', 'EVENT'),
('LitRPG', ' ', 'EVENT'),
('Little Romance', ' ', 'EVENT'),
('Livestreaming', ' ', 'EVENT'),
('Living Alone', ' ', 'EVENT'),
('Loli', ' ', 'EVENT'),
('Lolicon', ' ', 'EVENT'),
('Loneliness', ' ', 'EVENT'),
('Loner Protagonist', ' ', 'EVENT'),
('long lived main character', ' ', 'EVENT'),
('Long Separations', ' ', 'EVENT'),
('Lord of Mysteries', ' ', 'EVENT'),
('Lost Civilizations', ' ', 'EVENT'),
('Lottery', ' ', 'EVENT'),
('Love at First Sight', ' ', 'EVENT'),
('Love Interest Falls in Love First', ' ', 'EVENT'),
('Love Rivals', ' ', 'EVENT'),
('Love Triangles', ' ', 'EVENT'),
('Lovers Reunited', ' ', 'EVENT'),
('Low Fantasy', ' ', 'EVENT'),
('low Growth at Start', ' ', 'EVENT'),
('Low-key Protagonist', ' ', 'EVENT'),
('Loyal Subordinates', ' ', 'EVENT'),
('Lucky Protagonist', ' ', 'EVENT'),
('M*sturbation', ' ', 'EVENT'),
('Mage', ' ', 'EVENT'),
('Magic', ' ', 'EVENT'),
('Magic Academy', ' ', 'EVENT'),
('Magic Beasts', ' ', 'EVENT'),
('Magic Formations', ' ', 'EVENT'),
('Magic Realism', ' ', 'EVENT'),
('Magical Girls', ' ', 'EVENT'),
('Magical Space', ' ', 'EVENT'),
('Magical Technology', ' ', 'EVENT'),
('Mahouka Koukou No Rettousei', ' ', 'EVENT'),
('Maids', ' ', 'EVENT'),
('Male Lead', ' ', 'EVENT'),
('Male Protagonist', ' ', 'EVENT'),
('Male to Female', ' ', 'EVENT'),
('Male Yandere', ' ', 'EVENT'),
('Maleficent', ' ', 'EVENT'),
('Management', ' ', 'EVENT'),
('Manipulative Characters', ' ', 'EVENT'),
('Manly Gay Couple', ' ', 'EVENT'),
('Manton Effect', ' ', 'EVENT'),
('Marriage', ' ', 'EVENT'),
('Marriage of Convenience', ' ', 'EVENT'),
('Martial arts', ' ', 'EVENT'),
('Martial Peak', ' ', 'EVENT'),
('Martial Spirits', ' ', 'EVENT'),
('Marvel', ' ', 'EVENT'),
('Masochistic Characters', ' ', 'EVENT'),
('Massacre', ' ', 'EVENT'),
('Master-Disciple Relationship', ' ', 'EVENT'),
('Master-Servant Relationship', ' ', 'EVENT'),
('Masturbation', ' ', 'EVENT'),
('Matriarchy', ' ', 'EVENT'),
('Mature', ' ', 'EVENT'),
('Mature Protagonist', ' ', 'EVENT'),
('Mecha', ' ', 'EVENT'),
('Medical Knowledge', ' ', 'EVENT'),
('Medieval', ' ', 'EVENT'),
('Mercenaries', ' ', 'EVENT'),
('Merchants', ' ', 'EVENT'),
('Military', ' ', 'EVENT'),
('Mind Break', ' ', 'EVENT'),
('Mind Control', ' ', 'EVENT'),
('Minecraft', ' ', 'EVENT'),
('Mismatched Couple', ' ', 'EVENT'),
('Mistaken Identity', ' ', 'EVENT'),
('Misunderstandings', ' ', 'EVENT'),
('MMORPG', ' ', 'EVENT'),
('Mob Protagonist', ' ', 'EVENT'),
('Models', ' ', 'EVENT'),
('Modern Day', ' ', 'EVENT'),
('Modern Fantasy', ' ', 'EVENT'),
('Modern Knowledge', ' ', 'EVENT'),
('Modern Time', ' ', 'EVENT'),
('Modern World', ' ', 'EVENT'),
('Money Grubber', ' ', 'EVENT'),
('Monster Girls', ' ', 'EVENT'),
('Monster Society', ' ', 'EVENT'),
('Monster Tamer', ' ', 'EVENT'),
('Monsters', ' ', 'EVENT'),
('Movies', ' ', 'EVENT'),
('Mpreg', ' ', 'EVENT'),
('Multiple CP', ' ', 'EVENT'),
('Multiple Identities', ' ', 'EVENT'),
('Multiple Lead Characters', ' ', 'EVENT'),
('Multiple Personalities', ' ', 'EVENT'),
('Multiple POV', ' ', 'EVENT'),
('Multiple Povs', ' ', 'EVENT'),
('Multiple Protagonists', ' ', 'EVENT'),
('Multiple Realms', ' ', 'EVENT'),
('Multiple Reincarnated Individuals', ' ', 'EVENT'),
('Multiple Timelines', ' ', 'EVENT'),
('Multiple Transported Individuals', ' ', 'EVENT'),
('Multiverse', ' ', 'EVENT'),
('Murder', ' ', 'EVENT'),
('Murders', ' ', 'EVENT'),
('Music', ' ', 'EVENT'),
('Mutated Creatures', ' ', 'EVENT'),
('Mutations', ' ', 'EVENT'),
('Mute Character', ' ', 'EVENT'),
('My Hero Academia', ' ', 'EVENT'),
('My Wife Is A Beautiful CEO', ' ', 'EVENT'),
('Mysterious Family Background', ' ', 'EVENT'),
('Mysterious Illness', ' ', 'EVENT'),
('Mysterious Past', ' ', 'EVENT'),
('mystery', ' ', 'EVENT'),
('Mystery Solving', ' ', 'EVENT'),
('Mythical', ' ', 'EVENT'),
('Mythical Beasts', ' ', 'EVENT'),
('Mythology', ' ', 'EVENT'),
('Mythos', ' ', 'EVENT'),
('Naive Protagonist', ' ', 'EVENT'),
('Narcissistic Protagonist', ' ', 'EVENT'),
('Naruto', ' ', 'EVENT'),
('Nationalism', ' ', 'EVENT'),
('Near-Death Experience', ' ', 'EVENT'),
('Necromancer', ' ', 'EVENT'),
('Neet', ' ', 'EVENT'),
('Netorare', ' ', 'EVENT'),
('Netorase', ' ', 'EVENT'),
('Netori', ' ', 'EVENT'),
('Nightmares', ' ', 'EVENT'),
('Ninjas', ' ', 'EVENT'),
('No Cheats', ' ', 'EVENT'),
('No Harem', ' ', 'EVENT'),
('No Netorare', ' ', 'EVENT'),
('No Pairing', ' ', 'EVENT'),
('No Romance', ' ', 'EVENT'),
('No Yuri', ' ', 'EVENT'),
('Noble', ' ', 'EVENT'),
('Nobles', ' ', 'EVENT'),
('Non-Human lead', ' ', 'EVENT'),
('Non-human Protagonist', ' ', 'EVENT'),
('Non-humanoid Protagonist', ' ', 'EVENT'),
('Non-linear Storytelling', ' ', 'EVENT'),
('Not Harem', ' ', 'EVENT'),
('Not Netorare', ' ', 'EVENT'),
('Not Netori', ' ', 'EVENT'),
('Not so dumb Mc', ' ', 'EVENT'),
('Not Yaoi', ' ', 'EVENT'),
('NPC', ' ', 'EVENT'),
('Nudity', ' ', 'EVENT'),
('Nurses', ' ', 'EVENT'),
('Obsessive Love', ' ', 'EVENT'),
('Office Romance', ' ', 'EVENT'),
('Older Love Interests', ' ', 'EVENT'),
('Omegaverse', ' ', 'EVENT'),
('One Piece', ' ', 'EVENT'),
('One-Punch Man', ' ', 'EVENT'),
('Online Romance', ' ', 'EVENT'),
('Onmyouji', ' ', 'EVENT'),
('Or*y', ' ', 'EVENT'),
('Orcs', ' ', 'EVENT'),
('ordinary', ' ', 'EVENT'),
('Organized Crime', ' ', 'EVENT'),
('Orgy', ' ', 'EVENT'),
('Orphans', ' ', 'EVENT'),
('Otaku', ' ', 'EVENT'),
('Otome Game', ' ', 'EVENT'),
('Outcasts', ' ', 'EVENT'),
('Outdoor Interc**rse', ' ', 'EVENT'),
('Outer Space', ' ', 'EVENT'),
('Overlord', ' ', 'EVENT'),
('Overpowered', ' ', 'EVENT'),
('Overpowered Protagonist', ' ', 'EVENT'),
('Overprotective Siblings', ' ', 'EVENT'),
('Pacifist Protagonist', ' ', 'EVENT'),
('Paizuri', ' ', 'EVENT'),
('Parallel World', ' ', 'EVENT'),
('Parallel Worlds', ' ', 'EVENT'),
('Parasites', ' ', 'EVENT'),
('Parent Complex', ' ', 'EVENT'),
('Parody', ' ', 'EVENT'),
('Part-Time Job', ' ', 'EVENT'),
('Past Plays a Big Role', ' ', 'EVENT'),
('Past Trauma', ' ', 'EVENT'),
('Pe*verted Protagonist', ' ', 'EVENT'),
('Persistent Love Interests', ' ', 'EVENT'),
('Personality Changes', ' ', 'EVENT'),
('Perverted Protagonist', ' ', 'EVENT'),
('Pets', ' ', 'EVENT'),
('Pharmacist', ' ', 'EVENT'),
('Philosophical', ' ', 'EVENT'),
('Phobias', ' ', 'EVENT'),
('Phoenixes', ' ', 'EVENT'),
('Photography', ' ', 'EVENT'),
('Pill Based Cultivation', ' ', 'EVENT'),
('Pill Concocting', ' ', 'EVENT'),
('Pill Concoting', ' ', 'EVENT'),
('Pilots', ' ', 'EVENT'),
('Pirates', ' ', 'EVENT'),
('Planets', ' ', 'EVENT'),
('Playboys', ' ', 'EVENT'),
('Playful Protagonist', ' ', 'EVENT'),
('Poetry', ' ', 'EVENT'),
('Poisons', ' ', 'EVENT'),
('Pokemon', ' ', 'EVENT'),
('Police', ' ', 'EVENT'),
('Polite Protagonist', ' ', 'EVENT'),
('Political Systems', ' ', 'EVENT'),
('Politics', ' ', 'EVENT'),
('Polyandry', ' ', 'EVENT'),
('Polygamy', ' ', 'EVENT'),
('Poor Protagonist', ' ', 'EVENT'),
('Poor to Rich', ' ', 'EVENT'),
('Popular Love Interests', ' ', 'EVENT'),
('Portal Fantasy', ' ', 'EVENT'),
('Possession', ' ', 'EVENT'),
('Possessive Characters', ' ', 'EVENT'),
('Post-apocalyptic', ' ', 'EVENT'),
('Power Couple', ' ', 'EVENT'),
('Power Struggle', ' ', 'EVENT'),
('Pragmatic Protagonist', ' ', 'EVENT'),
('Precognition', ' ', 'EVENT'),
('Pregnancy', ' ', 'EVENT'),
('Pretend Lovers', ' ', 'EVENT'),
('Previous Life', ' ', 'EVENT'),
('Previous Life Talent', ' ', 'EVENT'),
('Priestesses', ' ', 'EVENT'),
('Priests', ' ', 'EVENT'),
('Prison', ' ', 'EVENT'),
('Proactive Protagonist', ' ', 'EVENT'),
('Programmer', ' ', 'EVENT'),
('Progression', ' ', 'EVENT'),
('Progression Fantasy', ' ', 'EVENT'),
('Prophecies', ' ', 'EVENT'),
('Prostit**es', ' ', 'EVENT'),
('Prostitutes', ' ', 'EVENT'),
('Protagonist Falls in Love First', ' ', 'EVENT'),
('Protagonist Loyal to Love Interest', ' ', 'EVENT'),
('Protagonist NPC', ' ', 'EVENT'),
('Protagonist Strong from the Start', ' ', 'EVENT'),
('Protagonist with Multiple Bodies', ' ', 'EVENT'),
('Pseudo Holographic Game', ' ', 'EVENT'),
('Pseudo Religions', ' ', 'EVENT'),
('Psychic Powers', ' ', 'EVENT'),
('Psychological', ' ', 'EVENT'),
('Psychopaths', ' ', 'EVENT'),
('PUBG', ' ', 'EVENT'),
('Puppeteers', ' ', 'EVENT'),
('Quick Transmigration', ' ', 'EVENT'),
('Quiet Characters', ' ', 'EVENT'),
('Quirky Characters', ' ', 'EVENT'),
('R-15', ' ', 'EVENT'),
('R-18', ' ', 'EVENT'),
('R*pe', ' ', 'EVENT'),
('R*pe Victim Becomes Lover', ' ', 'EVENT'),
('Race Change', ' ', 'EVENT'),
('Races', ' ', 'EVENT'),
('Racism', ' ', 'EVENT'),
('Raids', ' ', 'EVENT'),
('Rank System', ' ', 'EVENT'),
('Rape', ' ', 'EVENT'),
('Rape Victim Becomes Lover', ' ', 'EVENT'),
('Reader Interactive', ' ', 'EVENT'),
('RealRPG', ' ', 'EVENT'),
('Rebellion', ' ', 'EVENT'),
('Rebirth', ' ', 'EVENT'),
('Reckless Protagonist', ' ', 'EVENT'),
('Record of Ragnarok', ' ', 'EVENT'),
('Redemption', ' ', 'EVENT'),
('Reincarn', ' ', 'EVENT'),
('Reincarnated as a Monster', ' ', 'EVENT'),
('Reincarnated as an Object', ' ', 'EVENT'),
('Reincarnated in a Game World', ' ', 'EVENT'),
('Reincarnated in Another World', ' ', 'EVENT'),
('Reincarnated into a Game World', ' ', 'EVENT'),
('Reincarnated into Another World', ' ', 'EVENT'),
('Reincarnation', ' ', 'EVENT'),
('Religions', ' ', 'EVENT'),
('Reluctant Protagonist', ' ', 'EVENT'),
('Reporters', ' ', 'EVENT'),
('Resident Evil', ' ', 'EVENT'),
('Resolute Protagonist', ' ', 'EVENT'),
('Restaurant', ' ', 'EVENT'),
('Resurrection', ' ', 'EVENT'),
('Return of the Dragon King', ' ', 'EVENT'),
('Returning from Another World', ' ', 'EVENT'),
('Revenge', ' ', 'EVENT'),
('Reverse Harem', ' ', 'EVENT'),
('Reverse R*pe', ' ', 'EVENT'),
('Reverse Rape', ' ', 'EVENT'),
('Reversible Couple', ' ', 'EVENT'),
('Rich Protagonist', ' ', 'EVENT'),
('Rich to Poor', ' ', 'EVENT'),
('Righteous Protagonist', ' ', 'EVENT'),
('Rivalry', ' ', 'EVENT'),
('Romance', ' ', 'EVENT'),
('Romantic Subplot', ' ', 'EVENT'),
('Romantic Subplot Ruthless Protagonist', ' ', 'EVENT'),
('Roommates', ' ', 'EVENT'),
('Royalty', ' ', 'EVENT'),
('RPG', ' ', 'EVENT'),
('Ruling Class', ' ', 'EVENT'),
('Ruthless Protagonist', ' ', 'EVENT'),
('Ruthless Protagonist.', ' ', 'EVENT'),
('RWBY', ' ', 'EVENT'),
('S*ave Harem', ' ', 'EVENT'),
('S*ave Protagonist', ' ', 'EVENT'),
('S*aves', ' ', 'EVENT'),
('S*x Friends', ' ', 'EVENT'),
('S*x S*aves', ' ', 'EVENT'),
('S*xual Abuse', ' ', 'EVENT'),
('S*xual Cultivation Technique', ' ', 'EVENT'),
('Sadistic Characters', ' ', 'EVENT'),
('Saints', ' ', 'EVENT'),
('Salaryman', ' ', 'EVENT'),
('Samurai', ' ', 'EVENT'),
('Satire', ' ', 'EVENT'),
('Saving the World', ' ', 'EVENT'),
('Schemes And Conspiracies', ' ', 'EVENT'),
('Scheming', ' ', 'EVENT'),
('Scheming Protagonist', ' ', 'EVENT'),
('Schizophrenia', ' ', 'EVENT'),
('School Life', ' ', 'EVENT'),
('Sci-Fantasy', ' ', 'EVENT'),
('Sci-fi', ' ', 'EVENT'),
('sciencefiction', ' ', 'EVENT'),
('Scientists', ' ', 'EVENT'),
('SCP', ' ', 'EVENT'),
('Sculptors', ' ', 'EVENT'),
('Sealed Power', ' ', 'EVENT'),
('Second Chance', ' ', 'EVENT'),
('Secret Crush', ' ', 'EVENT'),
('Secret Identity', ' ', 'EVENT'),
('Secret Organization', ' ', 'EVENT'),
('Secret Organizations', ' ', 'EVENT'),
('Secret Relationship', ' ', 'EVENT'),
('Secretive Protagonist', ' ', 'EVENT'),
('Secrets', ' ', 'EVENT'),
('sect', ' ', 'EVENT'),
('Sect Development', ' ', 'EVENT'),
('Sects', ' ', 'EVENT'),
('Seduction', ' ', 'EVENT'),
('Seeing Things Other Humans Can''t', ' ', 'EVENT'),
('Selfish Protagonist', ' ', 'EVENT'),
('Selfless Protagonist', ' ', 'EVENT'),
('Seme Protagonist', ' ', 'EVENT'),
('Senpai-Kouhai Relationship', ' ', 'EVENT'),
('Sentient Objects', ' ', 'EVENT'),
('Sentimental Protagonist', ' ', 'EVENT'),
('Serial Killers', ' ', 'EVENT'),
('Servants', ' ', 'EVENT'),
('Seven Deadly Sins', ' ', 'EVENT'),
('Seven Virtues', ' ', 'EVENT'),
('Sex Friends', ' ', 'EVENT'),
('Sex Slaves', ' ', 'EVENT'),
('Sexual Abuse', ' ', 'EVENT'),
('Sexual Cultivation Technique', ' ', 'EVENT'),
('Shameless Protagonist', ' ', 'EVENT'),
('Shapeshifters', ' ', 'EVENT'),
('Sharing A Body', ' ', 'EVENT'),
('Sharp-tongued Characters', ' ', 'EVENT'),
('Shield User', ' ', 'EVENT'),
('Shikigami', ' ', 'EVENT'),
('Shinmai Mao no Tastement', ' ', 'EVENT'),
('Short Story', ' ', 'EVENT'),
('Shota', ' ', 'EVENT'),
('Shotacon', ' ', 'EVENT'),
('Shoujo-Ai Subplot', ' ', 'EVENT'),
('Shounen-Ai Subplot', ' ', 'EVENT'),
('Showbiz', ' ', 'EVENT'),
('Shy Characters', ' ', 'EVENT'),
('Sibling Rivalry', ' ', 'EVENT'),
('Sibling''s Care', ' ', 'EVENT'),
('Siblings', ' ', 'EVENT'),
('Siblings Not Related by Blood', ' ', 'EVENT'),
('Sickly Characters', ' ', 'EVENT'),
('Sign Language', ' ', 'EVENT'),
('Simulation', ' ', 'EVENT'),
('Singers', ' ', 'EVENT'),
('Single Parent', ' ', 'EVENT'),
('Sister Complex', ' ', 'EVENT'),
('Skill Assimilation', ' ', 'EVENT'),
('Skill Books', ' ', 'EVENT'),
('Skill Creation', ' ', 'EVENT'),
('Skyrim', ' ', 'EVENT'),
('Slave Harem', ' ', 'EVENT'),
('Slave Protagonist', ' ', 'EVENT'),
('Slaves', ' ', 'EVENT'),
('Sleeping', ' ', 'EVENT'),
('Sleeping Beauty', ' ', 'EVENT'),
('Slice of Life', ' ', 'EVENT'),
('Slow Cultivation', ' ', 'EVENT'),
('Slow Growth at Start', ' ', 'EVENT'),
('Slow Romance', ' ', 'EVENT'),
('slow-romance', ' ', 'EVENT'),
('Smart Couple', ' ', 'EVENT'),
('Smut', ' ', 'EVENT'),
('Social Outcasts', ' ', 'EVENT'),
('Soft Sci-fi', ' ', 'EVENT'),
('Soldiers', ' ', 'EVENT'),
('Solo Leveling', ' ', 'EVENT'),
('Soul Power', ' ', 'EVENT'),
('Souls', ' ', 'EVENT'),
('Sound Magic', ' ', 'EVENT'),
('Space', ' ', 'EVENT'),
('Space Opera', ' ', 'EVENT'),
('Spaceship', ' ', 'EVENT'),
('Spatial Manipulation', ' ', 'EVENT'),
('Spear Wielder', ' ', 'EVENT'),
('Spec', ' ', 'EVENT'),
('Special Abilitie', ' ', 'EVENT'),
('Special Abilities', ' ', 'EVENT'),
('Spies', ' ', 'EVENT'),
('Spirit Advisor', ' ', 'EVENT'),
('Spirit Users', ' ', 'EVENT'),
('Spirits', ' ', 'EVENT'),
('Sports', ' ', 'EVENT'),
('Sports Basketball', ' ', 'EVENT'),
('sportsbasketball', ' ', 'EVENT'),
('Stalkers', ' ', 'EVENT'),
('Star Trek', ' ', 'EVENT'),
('Star Wars', ' ', 'EVENT'),
('Steampunk', ' ', 'EVENT'),
('Stockholm Syndrome', ' ', 'EVENT'),
('Stoic Characters', ' ', 'EVENT'),
('Store Owner', ' ', 'EVENT'),
('Straight Uke', ' ', 'EVENT'),
('Strategic Battles', ' ', 'EVENT'),
('Strategist', ' ', 'EVENT'),
('Strategy', ' ', 'EVENT'),
('Strength-based Social Hierarchy', ' ', 'EVENT'),
('Strong from the Start', ' ', 'EVENT'),
('Strong Lead', ' ', 'EVENT'),
('Strong Love Interests', ' ', 'EVENT'),
('Strong Protagonist', ' ', 'EVENT'),
('Strong to Stronger', ' ', 'EVENT'),
('Stubborn Protagonist', ' ', 'EVENT'),
('Student Council', ' ', 'EVENT'),
('Student-Teacher Relationship', ' ', 'EVENT'),
('Subtle Romance', ' ', 'EVENT'),
('Succubus', ' ', 'EVENT'),
('Sudden Strength Gain', ' ', 'EVENT'),
('Sudden Wealth', ' ', 'EVENT'),
('Suicides', ' ', 'EVENT'),
('Summoned Hero', ' ', 'EVENT'),
('Summoning Magic', ' ', 'EVENT'),
('Super Heroes', ' ', 'EVENT'),
('super powers', ' ', 'EVENT'),
('supernatural', ' ', 'EVENT'),
('Superpowers', ' ', 'EVENT'),
('Survival', ' ', 'EVENT'),
('Survival Game', ' ', 'EVENT'),
('Sword And Magic', ' ', 'EVENT'),
('Sword Wielder', ' ', 'EVENT'),
('System', ' ', 'EVENT'),
('System Administration', ' ', 'EVENT'),
('System Administrator', ' ', 'EVENT'),
('Talent', ' ', 'EVENT'),
('Talent Prophecies', ' ', 'EVENT'),
('Tales of&nbsp;Demons and Gods', ' ', 'EVENT'),
('Teachers', ' ', 'EVENT'),
('Teamwork', ' ', 'EVENT'),
('Technological Gap', ' ', 'EVENT'),
('Technology Gap', ' ', 'EVENT'),
('Tentacles', ' ', 'EVENT'),
('Terminal Illness', ' ', 'EVENT'),
('Terrorists', ' ', 'EVENT'),
('The Asterisk War', ' ', 'EVENT'),
('The Devil Is a Part-Timer', ' ', 'EVENT'),
('The Gamer', ' ', 'EVENT'),
('The Modern world', ' ', 'EVENT'),
('The Pet Girl of Sakurasou', ' ', 'EVENT'),
('The Witcher', ' ', 'EVENT'),
('The Wizard of Oz', ' ', 'EVENT'),
('Thieves', ' ', 'EVENT'),
('Threesome', ' ', 'EVENT'),
('Thriller', ' ', 'EVENT'),
('Time Loop', ' ', 'EVENT'),
('Time Manipulation', ' ', 'EVENT'),
('Time Paradox', ' ', 'EVENT'),
('Time Skip', ' ', 'EVENT'),
('Time Travel', ' ', 'EVENT'),
('Timid Protagonist', ' ', 'EVENT'),
('Titans', ' ', 'EVENT'),
('Tokyo Ghoul', ' ', 'EVENT'),
('Tomboyish Female Lead', ' ', 'EVENT'),
('Torture', ' ', 'EVENT'),
('Toys', ' ', 'EVENT'),
('tragedy', ' ', 'EVENT'),
('Tragic Past', ' ', 'EVENT'),
('Transformation Ability', ' ', 'EVENT'),
('Transmigrated to another world', ' ', 'EVENT'),
('Transmigration', ' ', 'EVENT'),
('Transplanted Memories', ' ', 'EVENT'),
('Transported into a Game World', ' ', 'EVENT'),
('Transported into Another World', ' ', 'EVENT'),
('Transported Modern Structure', ' ', 'EVENT'),
('Transported to Another World', ' ', 'EVENT'),
('Trap', ' ', 'EVENT'),
('Travel Between Worlds', ' ', 'EVENT'),
('Tree Protagonist', ' ', 'EVENT'),
('Tribal Society', ' ', 'EVENT'),
('Trickster', ' ', 'EVENT'),
('Trolls', ' ', 'EVENT'),
('Tsundere', ' ', 'EVENT'),
('Tutorial', ' ', 'EVENT'),
('Twins', ' ', 'EVENT'),
('Twisted Personality', ' ', 'EVENT'),
('Type-Moon', ' ', 'EVENT'),
('Ugly Protagonist', ' ', 'EVENT'),
('Ugly to Beautiful', ' ', 'EVENT'),
('Unconditional Love', ' ', 'EVENT'),
('Underestimated Protagonist', ' ', 'EVENT'),
('Unique Cultivation Technique', ' ', 'EVENT'),
('Unique Weapon User', ' ', 'EVENT'),
('Unique Weapons', ' ', 'EVENT'),
('Unlimited Flow', ' ', 'EVENT'),
('Unlucky Protagonist', ' ', 'EVENT'),
('Unreliable Narrator', ' ', 'EVENT'),
('Unrequited Love', ' ', 'EVENT'),
('Urban', ' ', 'EVENT'),
('Urban Fantasy', ' ', 'EVENT'),
('Urban Life', ' ', 'EVENT'),
('Valkyries', ' ', 'EVENT'),
('Vampire', ' ', 'EVENT'),
('Vampires', ' ', 'EVENT'),
('VIDEOGAME', ' ', 'EVENT'),
('Villain', ' ', 'EVENT'),
('Villainess Noble Girls', ' ', 'EVENT'),
('Virtual Reality', ' ', 'EVENT'),
('Vocaloid', ' ', 'EVENT'),
('Voice Actors', ' ', 'EVENT'),
('Voyeurism', ' ', 'EVENT'),
('War Records', ' ', 'EVENT'),
('Warcaft', ' ', 'EVENT'),
('Warhammer', ' ', 'EVENT'),
('Warhammer 40K', ' ', 'EVENT'),
('Warlock of The Magus World', ' ', 'EVENT'),
('Wars', ' ', 'EVENT'),
('Wars Weak to Strong', ' ', 'EVENT'),
('Weak Protagonist', ' ', 'EVENT'),
('Weak to Strong', ' ', 'EVENT'),
('WEAKTOSTRONG', ' ', 'EVENT'),
('Wealthy Characters', ' ', 'EVENT'),
('Webnovel Spirity Awards', ' ', 'EVENT'),
('Week to Strong', ' ', 'EVENT'),
('Werebeasts', ' ', 'EVENT'),
('Westernization', ' ', 'EVENT'),
('Wishes', ' ', 'EVENT'),
('Witches', ' ', 'EVENT'),
('Wizards', ' ', 'EVENT'),
('World Background', ' ', 'EVENT'),
('World Building', ' ', 'EVENT'),
('World Hopping', ' ', 'EVENT'),
('World Invasion', ' ', 'EVENT'),
('World Travel', ' ', 'EVENT'),
('World Tree', ' ', 'EVENT'),
('Writers', ' ', 'EVENT'),
('Wuxia', ' ', 'EVENT'),
('X-men', ' ', 'EVENT'),
('Xianxia', ' ', 'EVENT'),
('Xuanhuan', ' ', 'EVENT'),
('Yandere', ' ', 'EVENT'),
('Youkai', ' ', 'EVENT'),
('Younger Brothers', ' ', 'EVENT'),
('Younger Love Interests', ' ', 'EVENT'),
('Younger Sisters', ' ', 'EVENT'),
('Zombies', ' ', 'EVENT')

ON CONFLICT DO NOTHING;